channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow>=2.20.0,<3.0.0
    - cloudpickle>=3.0.0
    - numpy>=1.24.0,<2.0.0
    - pandas>=2.0.0,<3.0.0
    - psutil>=5.9.0
    - scikit-learn>=1.3.0,<2.0.0
    - scipy>=1.10.0,<2.0.0

name: mlflow-env
