name: MLflow Train Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow numpy pandas scikit-learn scipy psutil

      - name: Run MLflow Project from Correct Local Path
        working-directory: ./Workflow-CI/MLProject
        run: |
          mlflow run . --no-conda
